import { Speaker, Notification, TeamMember, Ticket } from "./types";

export const mockTeamMembers: TeamMember[] = [
  { id: "1", name: "สมชาย ใจดี", email: "somchai@activity.com" },
  { id: "2", name: "สุดา มีสุข", email: "suda@activity.com" },
  { id: "3", name: "วิชัย เก่งมาก", email: "wichai@activity.com" },
  { id: "4", name: "นารี สวยงาม", email: "naree@activity.com" },
];

export const mockSpeakers: Speaker[] = [
  {
    id: "1",
    name: "ดร.พิชัย รัตนกุล",
    email: "pichai@university.ac.th",
    organization: "มหาวิทยาลัยเทคโนโลยี",
    title: "ผู้อำนวยการสถาบันนวัตกรรม",
    seminar_date: "2026-07-15",
    seminar_time: "09:00",
    seminar_end_time: "10:30",
    seminar_location: "ห้อง Auditorium A ชั้น 3",
    agenda_deadline: "2026-07-08",
    status: "confirmed",
    assigned_to: "1",
    portal_token: "abc123",
    notes: "วิทยากรหัวข้อ AI & Innovation",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "คุณสุภาพร วงศ์มณี",
    email: "supaporn@startup.co.th",
    organization: "Startup Thailand",
    title: "CEO & Co-Founder",
    seminar_date: "2026-07-15",
    seminar_time: "10:30",
    seminar_end_time: "12:00",
    seminar_location: "ห้อง Auditorium A ชั้น 3",
    agenda_deadline: "2026-07-08",
    status: "contacted",
    assigned_to: "2",
    portal_token: "def456",
    notes: "ขอหัวข้อ Entrepreneurship",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "ศาสตราจารย์ ดร.มานะ ชัยเจริญ",
    email: "mana@research.or.th",
    organization: "สถาบันวิจัยแห่งชาติ",
    title: "นักวิจัยอาวุโส",
    seminar_date: "2026-07-16",
    seminar_time: "13:00",
    seminar_end_time: "14:30",
    seminar_location: "ห้อง B201",
    agenda_deadline: "2026-07-09",
    status: "agenda_submitted",
    assigned_to: "1",
    portal_token: "ghi789",
    notes: "ส่ง Slide แล้ว รอ confirm ไฟล์เพิ่มเติม",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "คุณธนพล สินสมบัติ",
    email: "thanaphon@finance.co.th",
    organization: "บริษัทการเงินไทย",
    title: "ผู้จัดการอาวุโส",
    seminar_date: "2026-07-16",
    seminar_time: "14:30",
    seminar_end_time: "16:00",
    seminar_location: "ห้อง B201",
    agenda_deadline: "2026-07-09",
    status: "pending",
    assigned_to: "3",
    portal_token: "jkl012",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "ดร.วรรณา เพชรรัตน์",
    email: "wanna@tech.co.th",
    organization: "Tech Innovation Co.",
    title: "CTO",
    seminar_date: "2026-07-17",
    seminar_time: "09:00",
    seminar_end_time: "10:30",
    seminar_location: "ห้อง Main Hall",
    agenda_deadline: "2026-07-10",
    status: "confirmed",
    assigned_to: "4",
    portal_token: "mno345",
    notes: "หัวข้อ Digital Transformation",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "คุณอภิชาติ โกมลวิจิตร",
    email: "apichat@design.co.th",
    organization: "Creative Design Studio",
    title: "Creative Director",
    seminar_date: "2026-07-17",
    seminar_time: "11:00",
    seminar_end_time: "12:30",
    seminar_location: "ห้อง Main Hall",
    agenda_deadline: "2026-07-10",
    status: "cancelled",
    assigned_to: "2",
    portal_token: "pqr678",
    notes: "ติดภารกิจ ยกเลิกแล้ว",
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const mockTickets: Ticket[] = [
  {
    id: "t1",
    speaker_id: "1",
    subject: "สอบถามเรื่องการเดินทางและที่จอดรถ",
    message: "สวัสดีครับ อยากทราบว่ามีที่จอดรถสำหรับวิทยากรไหมครับ และสถานที่จัดงานอยู่ที่ไหนของอาคารครับ",
    status: "open",
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    replies: [],
  },
  {
    id: "t2",
    speaker_id: "3",
    subject: "ขอสอบถามเรื่อง projector และอุปกรณ์",
    message: "อยากทราบว่าห้องบรรยายมี projector ขนาดกี่นิ้วครับ และสามารถเชื่อมต่อ HDMI ได้ไหม ไฟล์ slide ผมเป็น PowerPoint ครับ",
    status: "replied",
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    updated_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    replies: [
      {
        id: "r1",
        message: "สวัสดีครับ อาจารย์ ห้อง B201 มี projector Full HD ขนาด 120 นิ้ว มี HDMI adapter ครบทุก connector พร้อมรีโมทเลเซอร์ไว้ให้ครับ",
        from: "team",
        author_name: "สมชาย ใจดี",
        created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
      },
    ],
  },
];

export const mockNotifications: Notification[] = [
  {
    id: "1",
    type: "ticket_opened",
    title: "Ticket ใหม่จากวิทยากร",
    message: "ดร.พิชัย รัตนกุล เปิด Ticket ถามเรื่องการเดินทาง",
    speaker_id: "1",
    speaker_name: "ดร.พิชัย รัตนกุล",
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: "2",
    type: "agenda_uploaded",
    title: "อัปโหลด Agenda แล้ว",
    message: "ศ.ดร.มานะ ชัยเจริญ อัปโหลดไฟล์ Slide เรียบร้อยแล้ว",
    speaker_id: "3",
    speaker_name: "ศ.ดร.มานะ ชัยเจริญ",
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: "3",
    type: "email_sent",
    title: "ส่งอีเมลสำเร็จ",
    message: "ส่งอีเมลยืนยันการนัดหมายให้ คุณสุภาพร วงศ์มณี เรียบร้อยแล้ว",
    speaker_id: "2",
    speaker_name: "คุณสุภาพร วงศ์มณี",
    read: true,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    id: "4",
    type: "deadline_approaching",
    title: "Deadline ใกล้แล้ว",
    message: "Deadline ส่ง Agenda ของ คุณธนพล สินสมบัติ เหลืออีก 2 วัน",
    speaker_id: "4",
    speaker_name: "คุณธนพล สินสมบัติ",
    read: false,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
];
